### ISSUE TITLE
UFRJ usa firewall

### ISSUE THREAD

**Issue by chinchila** [DantasB/Siga-Livre#1]
Oi,

A ufrj tem um firewall que tem ratelimit pra um certo cliente, se vc fizer vários requests o firewall vai bloquear, então acho que o site pode cair depois de um tempo.

A saída é ou fazer o request pelo client-side ou hospedar dentro da UFRJ.

**Comment by chinchila** [comment]
Ou usar cache | banco de dados

**Comment by DantasB** [comment]
@chinchila estou fazendo os testes para verificar se o host da azure tem esse problema. Independente do resultado, armazenarei os dados em um banco, visto que as requisições demoram um pouco. 
Até o momento realizei 2400 requisições e ainda não tomei bloqueio da UFRJ.

**Comment by DantasB** [comment]
@chinchila testei aqui e demorou umas 6400 requisições pra eu tomar block. Contudo o block não foi da UFRJ e sim do serviço de host que estou usando: AZURE

**Comment by DantasB** [comment]
A implementação do banco de dados foi realizada diminuindo o número de acessos ao domínio da UFRJ prevenindo o problema do Firewall
